// AUTO-GENERATED — do not edit. Run: bun run adapt:connectors
export const CONNECTOR_CATALOG = [
  { id: 'hunter', name: 'hunter', status: 'adapted' as const, path: './connectors-adapted/hunter' },
  {
    id: 'timelines-ai',
    name: 'timelines-ai',
    status: 'adapted' as const,
    path: './connectors-adapted/timelines-ai',
  },
  {
    id: 'vadoo-ai',
    name: 'vadoo-ai',
    status: 'adapted' as const,
    path: './connectors-adapted/vadoo-ai',
  },
  {
    id: 'air-ops',
    name: 'air-ops',
    status: 'adapted' as const,
    path: './connectors-adapted/air-ops',
  },
  {
    id: 'instabase',
    name: 'instabase',
    status: 'adapted' as const,
    path: './connectors-adapted/instabase',
  },
  {
    id: 'amazon-sqs',
    name: 'amazon-sqs',
    status: 'adapted' as const,
    path: './connectors-adapted/amazon-sqs',
  },
  {
    id: 'campaign-monitor',
    name: 'campaign-monitor',
    status: 'adapted' as const,
    path: './connectors-adapted/campaign-monitor',
  },
  {
    id: 'image-router',
    name: 'image-router',
    status: 'adapted' as const,
    path: './connectors-adapted/image-router',
  },
  {
    id: 'mailchain',
    name: 'mailchain',
    status: 'adapted' as const,
    path: './connectors-adapted/mailchain',
  },
  {
    id: 'cal-com',
    name: 'cal-com',
    status: 'adapted' as const,
    path: './connectors-adapted/cal-com',
  },
  {
    id: 'freshservice',
    name: 'freshservice',
    status: 'adapted' as const,
    path: './connectors-adapted/freshservice',
  },
  {
    id: 'omni-co',
    name: 'omni-co',
    status: 'adapted' as const,
    path: './connectors-adapted/omni-co',
  },
  {
    id: 'modelslab',
    name: 'modelslab',
    status: 'adapted' as const,
    path: './connectors-adapted/modelslab',
  },
  { id: 'plunk', name: 'plunk', status: 'adapted' as const, path: './connectors-adapted/plunk' },
  { id: 'attio', name: 'attio', status: 'adapted' as const, path: './connectors-adapted/attio' },
  { id: 'devin', name: 'devin', status: 'adapted' as const, path: './connectors-adapted/devin' },
  {
    id: 'granola',
    name: 'granola',
    status: 'adapted' as const,
    path: './connectors-adapted/granola',
  },
  {
    id: 'phone-validator',
    name: 'phone-validator',
    status: 'adapted' as const,
    path: './connectors-adapted/phone-validator',
  },
  {
    id: 'omnisend',
    name: 'omnisend',
    status: 'adapted' as const,
    path: './connectors-adapted/omnisend',
  },
  {
    id: 'postmark',
    name: 'postmark',
    status: 'adapted' as const,
    path: './connectors-adapted/postmark',
  },
  {
    id: 'writesonic-bulk',
    name: 'writesonic-bulk',
    status: 'adapted' as const,
    path: './connectors-adapted/writesonic-bulk',
  },
  { id: 'gamma', name: 'gamma', status: 'adapted' as const, path: './connectors-adapted/gamma' },
  { id: 'greip', name: 'greip', status: 'adapted' as const, path: './connectors-adapted/greip' },
  {
    id: 'time-ops',
    name: 'time-ops',
    status: 'adapted' as const,
    path: './connectors-adapted/time-ops',
  },
  { id: 'drip', name: 'drip', status: 'adapted' as const, path: './connectors-adapted/drip' },
  {
    id: 'freshdesk',
    name: 'freshdesk',
    status: 'adapted' as const,
    path: './connectors-adapted/freshdesk',
  },
  {
    id: 'generatebanners',
    name: 'generatebanners',
    status: 'adapted' as const,
    path: './connectors-adapted/generatebanners',
  },
  {
    id: 'microsoft-teams',
    name: 'microsoft-teams',
    status: 'adapted' as const,
    path: './connectors-adapted/microsoft-teams',
  },
  {
    id: 'brave-search',
    name: 'brave-search',
    status: 'adapted' as const,
    path: './connectors-adapted/brave-search',
  },
  {
    id: 'zendesk-sell',
    name: 'zendesk-sell',
    status: 'adapted' as const,
    path: './connectors-adapted/zendesk-sell',
  },
  {
    id: 'fillout-forms',
    name: 'fillout-forms',
    status: 'adapted' as const,
    path: './connectors-adapted/fillout-forms',
  },
  { id: 'lofty', name: 'lofty', status: 'adapted' as const, path: './connectors-adapted/lofty' },
  {
    id: 'moxie-crm',
    name: 'moxie-crm',
    status: 'adapted' as const,
    path: './connectors-adapted/moxie-crm',
  },
  {
    id: 'contentful',
    name: 'contentful',
    status: 'adapted' as const,
    path: './connectors-adapted/contentful',
  },
  {
    id: 'twin-labs',
    name: 'twin-labs',
    status: 'adapted' as const,
    path: './connectors-adapted/twin-labs',
  },
  {
    id: 'microsoft-power-bi',
    name: 'microsoft-power-bi',
    status: 'adapted' as const,
    path: './connectors-adapted/microsoft-power-bi',
  },
  {
    id: 'fliqr-ai',
    name: 'fliqr-ai',
    status: 'adapted' as const,
    path: './connectors-adapted/fliqr-ai',
  },
  { id: 'dust', name: 'dust', status: 'adapted' as const, path: './connectors-adapted/dust' },
  {
    id: 'chargebee',
    name: 'chargebee',
    status: 'adapted' as const,
    path: './connectors-adapted/chargebee',
  },
  {
    id: 'quizell',
    name: 'quizell',
    status: 'adapted' as const,
    path: './connectors-adapted/quizell',
  },
  { id: 'cohere', name: 'cohere', status: 'adapted' as const, path: './connectors-adapted/cohere' },
  { id: 'leexi', name: 'leexi', status: 'adapted' as const, path: './connectors-adapted/leexi' },
  {
    id: 'openmic-ai',
    name: 'openmic-ai',
    status: 'adapted' as const,
    path: './connectors-adapted/openmic-ai',
  },
  {
    id: 'oncehub',
    name: 'oncehub',
    status: 'adapted' as const,
    path: './connectors-adapted/oncehub',
  },
  {
    id: 'google-docs',
    name: 'google-docs',
    status: 'adapted' as const,
    path: './connectors-adapted/google-docs',
  },
  {
    id: 'webflow',
    name: 'webflow',
    status: 'adapted' as const,
    path: './connectors-adapted/webflow',
  },
  { id: 'omnihr', name: 'omnihr', status: 'adapted' as const, path: './connectors-adapted/omnihr' },
  {
    id: 'twitter',
    name: 'twitter',
    status: 'adapted' as const,
    path: './connectors-adapted/twitter',
  },
  {
    id: 'baserow',
    name: 'baserow',
    status: 'adapted' as const,
    path: './connectors-adapted/baserow',
  },
  {
    id: 'fountain',
    name: 'fountain',
    status: 'adapted' as const,
    path: './connectors-adapted/fountain',
  },
  {
    id: 'typefully',
    name: 'typefully',
    status: 'adapted' as const,
    path: './connectors-adapted/typefully',
  },
  { id: 'frill', name: 'frill', status: 'adapted' as const, path: './connectors-adapted/frill' },
  {
    id: 'mooninvoice',
    name: 'mooninvoice',
    status: 'adapted' as const,
    path: './connectors-adapted/mooninvoice',
  },
  { id: 'monday', name: 'monday', status: 'adapted' as const, path: './connectors-adapted/monday' },
  {
    id: 'visible',
    name: 'visible',
    status: 'adapted' as const,
    path: './connectors-adapted/visible',
  },
  {
    id: 'esignatures',
    name: 'esignatures',
    status: 'adapted' as const,
    path: './connectors-adapted/esignatures',
  },
  {
    id: 'lokalise',
    name: 'lokalise',
    status: 'adapted' as const,
    path: './connectors-adapted/lokalise',
  },
  {
    id: 'magicslides',
    name: 'magicslides',
    status: 'adapted' as const,
    path: './connectors-adapted/magicslides',
  },
  {
    id: 'chain-aware',
    name: 'chain-aware',
    status: 'adapted' as const,
    path: './connectors-adapted/chain-aware',
  },
  {
    id: 'truelayer',
    name: 'truelayer',
    status: 'adapted' as const,
    path: './connectors-adapted/truelayer',
  },
  {
    id: 'hackernews',
    name: 'hackernews',
    status: 'adapted' as const,
    path: './connectors-adapted/hackernews',
  },
  { id: 'aminos', name: 'aminos', status: 'adapted' as const, path: './connectors-adapted/aminos' },
  {
    id: 'woocommerce',
    name: 'woocommerce',
    status: 'adapted' as const,
    path: './connectors-adapted/woocommerce',
  },
  {
    id: 'scrapeless',
    name: 'scrapeless',
    status: 'adapted' as const,
    path: './connectors-adapted/scrapeless',
  },
  {
    id: 'productboard',
    name: 'productboard',
    status: 'adapted' as const,
    path: './connectors-adapted/productboard',
  },
  {
    id: 'salesloft',
    name: 'salesloft',
    status: 'adapted' as const,
    path: './connectors-adapted/salesloft',
  },
  {
    id: 'waitwhile',
    name: 'waitwhile',
    status: 'adapted' as const,
    path: './connectors-adapted/waitwhile',
  },
  {
    id: 'parallel',
    name: 'parallel',
    status: 'adapted' as const,
    path: './connectors-adapted/parallel',
  },
  { id: 'vero', name: 'vero', status: 'adapted' as const, path: './connectors-adapted/vero' },
  {
    id: 'editionguard',
    name: 'editionguard',
    status: 'adapted' as const,
    path: './connectors-adapted/editionguard',
  },
  {
    id: 'kudosity',
    name: 'kudosity',
    status: 'adapted' as const,
    path: './connectors-adapted/kudosity',
  },
  {
    id: 'sendfox',
    name: 'sendfox',
    status: 'adapted' as const,
    path: './connectors-adapted/sendfox',
  },
  {
    id: 'personal-ai',
    name: 'personal-ai',
    status: 'adapted' as const,
    path: './connectors-adapted/personal-ai',
  },
  {
    id: 'paywhirl',
    name: 'paywhirl',
    status: 'adapted' as const,
    path: './connectors-adapted/paywhirl',
  },
  {
    id: 'textcortex-ai',
    name: 'textcortex-ai',
    status: 'adapted' as const,
    path: './connectors-adapted/textcortex-ai',
  },
  {
    id: 'influencers-club',
    name: 'influencers-club',
    status: 'adapted' as const,
    path: './connectors-adapted/influencers-club',
  },
  {
    id: 'livesession',
    name: 'livesession',
    status: 'adapted' as const,
    path: './connectors-adapted/livesession',
  },
  { id: 'hedy', name: 'hedy', status: 'adapted' as const, path: './connectors-adapted/hedy' },
  { id: 'nocodb', name: 'nocodb', status: 'adapted' as const, path: './connectors-adapted/nocodb' },
  {
    id: 'azure-blob-storage',
    name: 'azure-blob-storage',
    status: 'adapted' as const,
    path: './connectors-adapted/azure-blob-storage',
  },
  {
    id: 'ghostcms',
    name: 'ghostcms',
    status: 'adapted' as const,
    path: './connectors-adapted/ghostcms',
  },
  {
    id: 'bannerbear',
    name: 'bannerbear',
    status: 'adapted' as const,
    path: './connectors-adapted/bannerbear',
  },
  {
    id: 'ask-handle',
    name: 'ask-handle',
    status: 'adapted' as const,
    path: './connectors-adapted/ask-handle',
  },
  {
    id: 'sap-ariba',
    name: 'sap-ariba',
    status: 'adapted' as const,
    path: './connectors-adapted/sap-ariba',
  },
  {
    id: 'http-oauth2',
    name: 'http-oauth2',
    status: 'adapted' as const,
    path: './connectors-adapted/http-oauth2',
  },
  {
    id: 'signrequest',
    name: 'signrequest',
    status: 'adapted' as const,
    path: './connectors-adapted/signrequest',
  },
  {
    id: 'clicksend',
    name: 'clicksend',
    status: 'adapted' as const,
    path: './connectors-adapted/clicksend',
  },
  {
    id: 'mempool-space',
    name: 'mempool-space',
    status: 'adapted' as const,
    path: './connectors-adapted/mempool-space',
  },
  { id: 'box', name: 'box', status: 'adapted' as const, path: './connectors-adapted/box' },
  { id: 'imap', name: 'imap', status: 'adapted' as const, path: './connectors-adapted/imap' },
  {
    id: 'discord',
    name: 'discord',
    status: 'adapted' as const,
    path: './connectors-adapted/discord',
  },
  { id: 'smaily', name: 'smaily', status: 'adapted' as const, path: './connectors-adapted/smaily' },
  {
    id: 'zoho-books',
    name: 'zoho-books',
    status: 'adapted' as const,
    path: './connectors-adapted/zoho-books',
  },
  {
    id: 'simplybookme',
    name: 'simplybookme',
    status: 'adapted' as const,
    path: './connectors-adapted/simplybookme',
  },
  {
    id: 'clockodo',
    name: 'clockodo',
    status: 'adapted' as const,
    path: './connectors-adapted/clockodo',
  },
  {
    id: 'goodmem',
    name: 'goodmem',
    status: 'adapted' as const,
    path: './connectors-adapted/goodmem',
  },
  { id: 'vercel', name: 'vercel', status: 'adapted' as const, path: './connectors-adapted/vercel' },
  {
    id: 'clickfunnels',
    name: 'clickfunnels',
    status: 'adapted' as const,
    path: './connectors-adapted/clickfunnels',
  },
  {
    id: 'docusign',
    name: 'docusign',
    status: 'adapted' as const,
    path: './connectors-adapted/docusign',
  },
  {
    id: 'surrealdb',
    name: 'surrealdb',
    status: 'adapted' as const,
    path: './connectors-adapted/surrealdb',
  },
  {
    id: 'kizeo-forms',
    name: 'kizeo-forms',
    status: 'adapted' as const,
    path: './connectors-adapted/kizeo-forms',
  },
  {
    id: 'socialkit',
    name: 'socialkit',
    status: 'adapted' as const,
    path: './connectors-adapted/socialkit',
  },
  { id: 'close', name: 'close', status: 'adapted' as const, path: './connectors-adapted/close' },
  {
    id: 'tableau',
    name: 'tableau',
    status: 'adapted' as const,
    path: './connectors-adapted/tableau',
  },
  {
    id: 'microsoft-sharepoint',
    name: 'microsoft-sharepoint',
    status: 'adapted' as const,
    path: './connectors-adapted/microsoft-sharepoint',
  },
  { id: 'senja', name: 'senja', status: 'adapted' as const, path: './connectors-adapted/senja' },
  {
    id: 'greenhouse',
    name: 'greenhouse',
    status: 'adapted' as const,
    path: './connectors-adapted/greenhouse',
  },
  {
    id: 'what-converts',
    name: 'what-converts',
    status: 'adapted' as const,
    path: './connectors-adapted/what-converts',
  },
  {
    id: 'chartly',
    name: 'chartly',
    status: 'adapted' as const,
    path: './connectors-adapted/chartly',
  },
  {
    id: 'chatwoot',
    name: 'chatwoot',
    status: 'adapted' as const,
    path: './connectors-adapted/chatwoot',
  },
  { id: 'bexio', name: 'bexio', status: 'adapted' as const, path: './connectors-adapted/bexio' },
  {
    id: 'wonderchat',
    name: 'wonderchat',
    status: 'adapted' as const,
    path: './connectors-adapted/wonderchat',
  },
  {
    id: 'grok-xai',
    name: 'grok-xai',
    status: 'adapted' as const,
    path: './connectors-adapted/grok-xai',
  },
  { id: 'gitlab', name: 'gitlab', status: 'adapted' as const, path: './connectors-adapted/gitlab' },
  {
    id: 'cyberark',
    name: 'cyberark',
    status: 'adapted' as const,
    path: './connectors-adapted/cyberark',
  },
  {
    id: 'dashworks',
    name: 'dashworks',
    status: 'adapted' as const,
    path: './connectors-adapted/dashworks',
  },
  {
    id: 'azure-ad',
    name: 'azure-ad',
    status: 'adapted' as const,
    path: './connectors-adapted/azure-ad',
  },
  {
    id: 'formitable',
    name: 'formitable',
    status: 'adapted' as const,
    path: './connectors-adapted/formitable',
  },
  {
    id: 'messagebird',
    name: 'messagebird',
    status: 'adapted' as const,
    path: './connectors-adapted/messagebird',
  },
  { id: 'telnyx', name: 'telnyx', status: 'adapted' as const, path: './connectors-adapted/telnyx' },
  {
    id: 'mycase-piece',
    name: 'mycase-piece',
    status: 'adapted' as const,
    path: './connectors-adapted/mycase-piece',
  },
  {
    id: 'plausible',
    name: 'plausible',
    status: 'adapted' as const,
    path: './connectors-adapted/plausible',
  },
  { id: 'drupal', name: 'drupal', status: 'adapted' as const, path: './connectors-adapted/drupal' },
  {
    id: 'raindrop',
    name: 'raindrop',
    status: 'adapted' as const,
    path: './connectors-adapted/raindrop',
  },
  {
    id: 'webscraping-ai',
    name: 'webscraping-ai',
    status: 'adapted' as const,
    path: './connectors-adapted/webscraping-ai',
  },
  {
    id: 'kissflow',
    name: 'kissflow',
    status: 'adapted' as const,
    path: './connectors-adapted/kissflow',
  },
  {
    id: 'hume-ai',
    name: 'hume-ai',
    status: 'adapted' as const,
    path: './connectors-adapted/hume-ai',
  },
  {
    id: 'manychat',
    name: 'manychat',
    status: 'adapted' as const,
    path: './connectors-adapted/manychat',
  },
  {
    id: 'pinterest',
    name: 'pinterest',
    status: 'adapted' as const,
    path: './connectors-adapted/pinterest',
  },
  { id: 'strale', name: 'strale', status: 'adapted' as const, path: './connectors-adapted/strale' },
  {
    id: 'comfyicu',
    name: 'comfyicu',
    status: 'adapted' as const,
    path: './connectors-adapted/comfyicu',
  },
  {
    id: 'chaindesk',
    name: 'chaindesk',
    status: 'adapted' as const,
    path: './connectors-adapted/chaindesk',
  },
  {
    id: 'meetgeek-ai',
    name: 'meetgeek-ai',
    status: 'adapted' as const,
    path: './connectors-adapted/meetgeek-ai',
  },
  { id: 'mixmax', name: 'mixmax', status: 'adapted' as const, path: './connectors-adapted/mixmax' },
  {
    id: 'telegram-bot',
    name: 'telegram-bot',
    status: 'adapted' as const,
    path: './connectors-adapted/telegram-bot',
  },
  {
    id: 'insighto-ai',
    name: 'insighto-ai',
    status: 'adapted' as const,
    path: './connectors-adapted/insighto-ai',
  },
  {
    id: 'google-search',
    name: 'google-search',
    status: 'adapted' as const,
    path: './connectors-adapted/google-search',
  },
  {
    id: 'google-vertexai',
    name: 'google-vertexai',
    status: 'adapted' as const,
    path: './connectors-adapted/google-vertexai',
  },
  {
    id: 'microsoft-excel-365',
    name: 'microsoft-excel-365',
    status: 'adapted' as const,
    path: './connectors-adapted/microsoft-excel-365',
  },
  {
    id: 'chess-com',
    name: 'chess-com',
    status: 'adapted' as const,
    path: './connectors-adapted/chess-com',
  },
  {
    id: 'wordpress',
    name: 'wordpress',
    status: 'adapted' as const,
    path: './connectors-adapted/wordpress',
  },
  {
    id: 'returning-ai',
    name: 'returning-ai',
    status: 'adapted' as const,
    path: './connectors-adapted/returning-ai',
  },
  {
    id: 'quaderno',
    name: 'quaderno',
    status: 'adapted' as const,
    path: './connectors-adapted/quaderno',
  },
  { id: 'umami', name: 'umami', status: 'adapted' as const, path: './connectors-adapted/umami' },
  {
    id: 'pinch-payments',
    name: 'pinch-payments',
    status: 'adapted' as const,
    path: './connectors-adapted/pinch-payments',
  },
  { id: 'glide', name: 'glide', status: 'adapted' as const, path: './connectors-adapted/glide' },
  {
    id: 'swarmnode',
    name: 'swarmnode',
    status: 'adapted' as const,
    path: './connectors-adapted/swarmnode',
  },
  {
    id: 'heymarket-sms',
    name: 'heymarket-sms',
    status: 'adapted' as const,
    path: './connectors-adapted/heymarket-sms',
  },
  {
    id: 'mastodon',
    name: 'mastodon',
    status: 'adapted' as const,
    path: './connectors-adapted/mastodon',
  },
  {
    id: 'octopush-sms',
    name: 'octopush-sms',
    status: 'adapted' as const,
    path: './connectors-adapted/octopush-sms',
  },
  {
    id: 'savvycal',
    name: 'savvycal',
    status: 'adapted' as const,
    path: './connectors-adapted/savvycal',
  },
  {
    id: 'respond-io',
    name: 'respond-io',
    status: 'adapted' as const,
    path: './connectors-adapted/respond-io',
  },
  {
    id: 'slashed',
    name: 'slashed',
    status: 'adapted' as const,
    path: './connectors-adapted/slashed',
  },
  { id: 'bitly', name: 'bitly', status: 'adapted' as const, path: './connectors-adapted/bitly' },
  { id: 'cursor', name: 'cursor', status: 'adapted' as const, path: './connectors-adapted/cursor' },
  {
    id: 'tidycal',
    name: 'tidycal',
    status: 'adapted' as const,
    path: './connectors-adapted/tidycal',
  },
  {
    id: 'simplyprint',
    name: 'simplyprint',
    status: 'adapted' as const,
    path: './connectors-adapted/simplyprint',
  },
  {
    id: 'microsoft-copilot',
    name: 'microsoft-copilot',
    status: 'adapted' as const,
    path: './connectors-adapted/microsoft-copilot',
  },
  {
    id: 'formsite',
    name: 'formsite',
    status: 'adapted' as const,
    path: './connectors-adapted/formsite',
  },
  {
    id: 'quickbase',
    name: 'quickbase',
    status: 'adapted' as const,
    path: './connectors-adapted/quickbase',
  },
  { id: 'smoove', name: 'smoove', status: 'adapted' as const, path: './connectors-adapted/smoove' },
  { id: 'pylon', name: 'pylon', status: 'adapted' as const, path: './connectors-adapted/pylon' },
  {
    id: 'flipando',
    name: 'flipando',
    status: 'adapted' as const,
    path: './connectors-adapted/flipando',
  },
  {
    id: 'oracle-fusion-cloud-erp',
    name: 'oracle-fusion-cloud-erp',
    status: 'adapted' as const,
    path: './connectors-adapted/oracle-fusion-cloud-erp',
  },
  {
    id: 'workday',
    name: 'workday',
    status: 'adapted' as const,
    path: './connectors-adapted/workday',
  },
  { id: 'wistia', name: 'wistia', status: 'adapted' as const, path: './connectors-adapted/wistia' },
  { id: 'zeplin', name: 'zeplin', status: 'adapted' as const, path: './connectors-adapted/zeplin' },
  {
    id: 'alt-text-ai',
    name: 'alt-text-ai',
    status: 'adapted' as const,
    path: './connectors-adapted/alt-text-ai',
  },
  {
    id: 'opnform',
    name: 'opnform',
    status: 'adapted' as const,
    path: './connectors-adapted/opnform',
  },
  { id: 'streak', name: 'streak', status: 'adapted' as const, path: './connectors-adapted/streak' },
  {
    id: 'localai',
    name: 'localai',
    status: 'adapted' as const,
    path: './connectors-adapted/localai',
  },
  {
    id: 'microsoft-dynamics-365-business-central',
    name: 'microsoft-dynamics-365-business-central',
    status: 'adapted' as const,
    path: './connectors-adapted/microsoft-dynamics-365-business-central',
  },
  {
    id: 'sendgrid',
    name: 'sendgrid',
    status: 'adapted' as const,
    path: './connectors-adapted/sendgrid',
  },
  {
    id: 'bamboohr',
    name: 'bamboohr',
    status: 'adapted' as const,
    path: './connectors-adapted/bamboohr',
  },
  {
    id: 'backblaze',
    name: 'backblaze',
    status: 'adapted' as const,
    path: './connectors-adapted/backblaze',
  },
  {
    id: 'predis-ai',
    name: 'predis-ai',
    status: 'adapted' as const,
    path: './connectors-adapted/predis-ai',
  },
  {
    id: 'bigin-by-zoho',
    name: 'bigin-by-zoho',
    status: 'adapted' as const,
    path: './connectors-adapted/bigin-by-zoho',
  },
  {
    id: 'airparser',
    name: 'airparser',
    status: 'adapted' as const,
    path: './connectors-adapted/airparser',
  },
  { id: 'mautic', name: 'mautic', status: 'adapted' as const, path: './connectors-adapted/mautic' },
  {
    id: 'open-phone',
    name: 'open-phone',
    status: 'adapted' as const,
    path: './connectors-adapted/open-phone',
  },
  {
    id: 'getresponse',
    name: 'getresponse',
    status: 'adapted' as const,
    path: './connectors-adapted/getresponse',
  },
  {
    id: 'imeetify',
    name: 'imeetify',
    status: 'adapted' as const,
    path: './connectors-adapted/imeetify',
  },
  {
    id: 'tarvent',
    name: 'tarvent',
    status: 'adapted' as const,
    path: './connectors-adapted/tarvent',
  },
  { id: 'placid', name: 'placid', status: 'adapted' as const, path: './connectors-adapted/placid' },
  {
    id: 'lobstermail',
    name: 'lobstermail',
    status: 'adapted' as const,
    path: './connectors-adapted/lobstermail',
  },
  {
    id: 'smartsuite',
    name: 'smartsuite',
    status: 'adapted' as const,
    path: './connectors-adapted/smartsuite',
  },
  { id: 'pendo', name: 'pendo', status: 'adapted' as const, path: './connectors-adapted/pendo' },
  {
    id: 'scrapegrapghai',
    name: 'scrapegrapghai',
    status: 'adapted' as const,
    path: './connectors-adapted/scrapegrapghai',
  },
  {
    id: 'apitable',
    name: 'apitable',
    status: 'adapted' as const,
    path: './connectors-adapted/apitable',
  },
  {
    id: 'prompthub',
    name: 'prompthub',
    status: 'adapted' as const,
    path: './connectors-adapted/prompthub',
  },
  {
    id: 'qawafel',
    name: 'qawafel',
    status: 'adapted' as const,
    path: './connectors-adapted/qawafel',
  },
  {
    id: 'sign-now',
    name: 'sign-now',
    status: 'adapted' as const,
    path: './connectors-adapted/sign-now',
  },
  {
    id: 'captain-data',
    name: 'captain-data',
    status: 'adapted' as const,
    path: './connectors-adapted/captain-data',
  },
  { id: 'mindee', name: 'mindee', status: 'adapted' as const, path: './connectors-adapted/mindee' },
  {
    id: 'fireberry',
    name: 'fireberry',
    status: 'adapted' as const,
    path: './connectors-adapted/fireberry',
  },
  {
    id: 'smsmode',
    name: 'smsmode',
    status: 'adapted' as const,
    path: './connectors-adapted/smsmode',
  },
  {
    id: 'just-invoice',
    name: 'just-invoice',
    status: 'adapted' as const,
    path: './connectors-adapted/just-invoice',
  },
  { id: 'sendr', name: 'sendr', status: 'adapted' as const, path: './connectors-adapted/sendr' },
  { id: 'runway', name: 'runway', status: 'adapted' as const, path: './connectors-adapted/runway' },
  {
    id: 'firecrawl',
    name: 'firecrawl',
    status: 'adapted' as const,
    path: './connectors-adapted/firecrawl',
  },
  {
    id: 'foreplay-co',
    name: 'foreplay-co',
    status: 'adapted' as const,
    path: './connectors-adapted/foreplay-co',
  },
  {
    id: 'microsoft-onedrive',
    name: 'microsoft-onedrive',
    status: 'adapted' as const,
    path: './connectors-adapted/microsoft-onedrive',
  },
  {
    id: 'zoho-invoice',
    name: 'zoho-invoice',
    status: 'adapted' as const,
    path: './connectors-adapted/zoho-invoice',
  },
  {
    id: 'activecampaign',
    name: 'activecampaign',
    status: 'adapted' as const,
    path: './connectors-adapted/activecampaign',
  },
  { id: 'xero', name: 'xero', status: 'adapted' as const, path: './connectors-adapted/xero' },
  { id: 'teable', name: 'teable', status: 'adapted' as const, path: './connectors-adapted/teable' },
  {
    id: 'hystruct',
    name: 'hystruct',
    status: 'adapted' as const,
    path: './connectors-adapted/hystruct',
  },
  { id: 'gladia', name: 'gladia', status: 'adapted' as const, path: './connectors-adapted/gladia' },
  {
    id: 'detecting-ai',
    name: 'detecting-ai',
    status: 'adapted' as const,
    path: './connectors-adapted/detecting-ai',
  },
  {
    id: 'invoiceninja',
    name: 'invoiceninja',
    status: 'adapted' as const,
    path: './connectors-adapted/invoiceninja',
  },
  {
    id: 'acumbamail',
    name: 'acumbamail',
    status: 'adapted' as const,
    path: './connectors-adapted/acumbamail',
  },
  {
    id: 'actualbudget',
    name: 'actualbudget',
    status: 'adapted' as const,
    path: './connectors-adapted/actualbudget',
  },
  {
    id: 'validatedmails',
    name: 'validatedmails',
    status: 'adapted' as const,
    path: './connectors-adapted/validatedmails',
  },
  {
    id: 'pagerduty',
    name: 'pagerduty',
    status: 'adapted' as const,
    path: './connectors-adapted/pagerduty',
  },
  {
    id: 'paperform',
    name: 'paperform',
    status: 'adapted' as const,
    path: './connectors-adapted/paperform',
  },
  {
    id: 'send-it',
    name: 'send-it',
    status: 'adapted' as const,
    path: './connectors-adapted/send-it',
  },
  {
    id: 'chatbase',
    name: 'chatbase',
    status: 'adapted' as const,
    path: './connectors-adapted/chatbase',
  },
  {
    id: 'wealthbox',
    name: 'wealthbox',
    status: 'adapted' as const,
    path: './connectors-adapted/wealthbox',
  },
  {
    id: 'klaviyo',
    name: 'klaviyo',
    status: 'adapted' as const,
    path: './connectors-adapted/klaviyo',
  },
  {
    id: 'village',
    name: 'village',
    status: 'adapted' as const,
    path: './connectors-adapted/village',
  },
  {
    id: 'microsoft-365-people',
    name: 'microsoft-365-people',
    status: 'adapted' as const,
    path: './connectors-adapted/microsoft-365-people',
  },
  { id: 'claude', name: 'claude', status: 'adapted' as const, path: './connectors-adapted/claude' },
  {
    id: 'famulor',
    name: 'famulor',
    status: 'adapted' as const,
    path: './connectors-adapted/famulor',
  },
  { id: 'wrike', name: 'wrike', status: 'adapted' as const, path: './connectors-adapted/wrike' },
  {
    id: 'smartsheet',
    name: 'smartsheet',
    status: 'adapted' as const,
    path: './connectors-adapted/smartsheet',
  },
  {
    id: 'lead-connector',
    name: 'lead-connector',
    status: 'adapted' as const,
    path: './connectors-adapted/lead-connector',
  },
  {
    id: 'amazon-sns',
    name: 'amazon-sns',
    status: 'adapted' as const,
    path: './connectors-adapted/amazon-sns',
  },
  {
    id: 'jungle-grid',
    name: 'jungle-grid',
    status: 'adapted' as const,
    path: './connectors-adapted/jungle-grid',
  },
  { id: 'square', name: 'square', status: 'adapted' as const, path: './connectors-adapted/square' },
  {
    id: 'easy-peasy-ai',
    name: 'easy-peasy-ai',
    status: 'adapted' as const,
    path: './connectors-adapted/easy-peasy-ai',
  },
  {
    id: 'spotify',
    name: 'spotify',
    status: 'adapted' as const,
    path: './connectors-adapted/spotify',
  },
  { id: 'copper', name: 'copper', status: 'adapted' as const, path: './connectors-adapted/copper' },
  { id: 'odoo', name: 'odoo', status: 'adapted' as const, path: './connectors-adapted/odoo' },
  {
    id: 'presenton',
    name: 'presenton',
    status: 'adapted' as const,
    path: './connectors-adapted/presenton',
  },
  {
    id: 'maileroo',
    name: 'maileroo',
    status: 'adapted' as const,
    path: './connectors-adapted/maileroo',
  },
  {
    id: 'provenexpert',
    name: 'provenexpert',
    status: 'adapted' as const,
    path: './connectors-adapted/provenexpert',
  },
  { id: 'poper', name: 'poper', status: 'adapted' as const, path: './connectors-adapted/poper' },
  {
    id: 'llmrails',
    name: 'llmrails',
    status: 'adapted' as const,
    path: './connectors-adapted/llmrails',
  },
  {
    id: 'bigcommerce',
    name: 'bigcommerce',
    status: 'adapted' as const,
    path: './connectors-adapted/bigcommerce',
  },
  {
    id: 'freshsales',
    name: 'freshsales',
    status: 'adapted' as const,
    path: './connectors-adapted/freshsales',
  },
  { id: 'vidnoz', name: 'vidnoz', status: 'adapted' as const, path: './connectors-adapted/vidnoz' },
  {
    id: 'pipedrive',
    name: 'pipedrive',
    status: 'adapted' as const,
    path: './connectors-adapted/pipedrive',
  },
  {
    id: 'youform',
    name: 'youform',
    status: 'adapted' as const,
    path: './connectors-adapted/youform',
  },
  { id: 'valyu', name: 'valyu', status: 'adapted' as const, path: './connectors-adapted/valyu' },
  {
    id: 'datocms',
    name: 'datocms',
    status: 'adapted' as const,
    path: './connectors-adapted/datocms',
  },
  {
    id: 'google-forms',
    name: 'google-forms',
    status: 'adapted' as const,
    path: './connectors-adapted/google-forms',
  },
  {
    id: 'sessions-us',
    name: 'sessions-us',
    status: 'adapted' as const,
    path: './connectors-adapted/sessions-us',
  },
  { id: 'linear', name: 'linear', status: 'adapted' as const, path: './connectors-adapted/linear' },
  {
    id: 'guidelite',
    name: 'guidelite',
    status: 'adapted' as const,
    path: './connectors-adapted/guidelite',
  },
  { id: 'flowlu', name: 'flowlu', status: 'adapted' as const, path: './connectors-adapted/flowlu' },
  { id: 'vtex', name: 'vtex', status: 'adapted' as const, path: './connectors-adapted/vtex' },
  {
    id: 'mailjet',
    name: 'mailjet',
    status: 'adapted' as const,
    path: './connectors-adapted/mailjet',
  },
  {
    id: 'zoho-campaigns',
    name: 'zoho-campaigns',
    status: 'adapted' as const,
    path: './connectors-adapted/zoho-campaigns',
  },
  {
    id: 'segment',
    name: 'segment',
    status: 'adapted' as const,
    path: './connectors-adapted/segment',
  },
  {
    id: 'convertkit',
    name: 'convertkit',
    status: 'adapted' as const,
    path: './connectors-adapted/convertkit',
  },
  {
    id: 'cognito-forms',
    name: 'cognito-forms',
    status: 'adapted' as const,
    path: './connectors-adapted/cognito-forms',
  },
  {
    id: 'baremetrics',
    name: 'baremetrics',
    status: 'adapted' as const,
    path: './connectors-adapted/baremetrics',
  },
  {
    id: 'rapidtext-ai',
    name: 'rapidtext-ai',
    status: 'adapted' as const,
    path: './connectors-adapted/rapidtext-ai',
  },
  { id: 'exa', name: 'exa', status: 'adapted' as const, path: './connectors-adapted/exa' },
  {
    id: 'jira-data-center',
    name: 'jira-data-center',
    status: 'adapted' as const,
    path: './connectors-adapted/jira-data-center',
  },
  {
    id: 'chat-data',
    name: 'chat-data',
    status: 'adapted' as const,
    path: './connectors-adapted/chat-data',
  },
  {
    id: 'acuity-scheduling',
    name: 'acuity-scheduling',
    status: 'adapted' as const,
    path: './connectors-adapted/acuity-scheduling',
  },
  { id: 'lever', name: 'lever', status: 'adapted' as const, path: './connectors-adapted/lever' },
  { id: 'sender', name: 'sender', status: 'adapted' as const, path: './connectors-adapted/sender' },
  { id: 'rss', name: 'rss', status: 'adapted' as const, path: './connectors-adapted/rss' },
  {
    id: 'tapfiliate',
    name: 'tapfiliate',
    status: 'adapted' as const,
    path: './connectors-adapted/tapfiliate',
  },
  { id: 'vimeo', name: 'vimeo', status: 'adapted' as const, path: './connectors-adapted/vimeo' },
  {
    id: 'hashi-corp-vault',
    name: 'hashi-corp-vault',
    status: 'adapted' as const,
    path: './connectors-adapted/hashi-corp-vault',
  },
  {
    id: 'parser-expert',
    name: 'parser-expert',
    status: 'adapted' as const,
    path: './connectors-adapted/parser-expert',
  },
  { id: 'orimon', name: 'orimon', status: 'adapted' as const, path: './connectors-adapted/orimon' },
  {
    id: 'intercom',
    name: 'intercom',
    status: 'adapted' as const,
    path: './connectors-adapted/intercom',
  },
  {
    id: 'autocalls',
    name: 'autocalls',
    status: 'adapted' as const,
    path: './connectors-adapted/autocalls',
  },
  {
    id: 'peekshot',
    name: 'peekshot',
    status: 'adapted' as const,
    path: './connectors-adapted/peekshot',
  },
  { id: 'paddle', name: 'paddle', status: 'adapted' as const, path: './connectors-adapted/paddle' },
  {
    id: 'denser-ai',
    name: 'denser-ai',
    status: 'adapted' as const,
    path: './connectors-adapted/denser-ai',
  },
  { id: 'softr', name: 'softr', status: 'adapted' as const, path: './connectors-adapted/softr' },
  {
    id: 'zagomail',
    name: 'zagomail',
    status: 'adapted' as const,
    path: './connectors-adapted/zagomail',
  },
  {
    id: 'workable',
    name: 'workable',
    status: 'adapted' as const,
    path: './connectors-adapted/workable',
  },
  { id: 'ntfy', name: 'ntfy', status: 'adapted' as const, path: './connectors-adapted/ntfy' },
  {
    id: 'pdfmonkey',
    name: 'pdfmonkey',
    status: 'adapted' as const,
    path: './connectors-adapted/pdfmonkey',
  },
  {
    id: 'google-tasks',
    name: 'google-tasks',
    status: 'adapted' as const,
    path: './connectors-adapted/google-tasks',
  },
  { id: 'vtiger', name: 'vtiger', status: 'adapted' as const, path: './connectors-adapted/vtiger' },
  {
    id: 'talkable',
    name: 'talkable',
    status: 'adapted' as const,
    path: './connectors-adapted/talkable',
  },
  {
    id: 'cloudinary',
    name: 'cloudinary',
    status: 'adapted' as const,
    path: './connectors-adapted/cloudinary',
  },
  {
    id: 'shopify',
    name: 'shopify',
    status: 'adapted' as const,
    path: './connectors-adapted/shopify',
  },
  {
    id: 'deepgram',
    name: 'deepgram',
    status: 'adapted' as const,
    path: './connectors-adapted/deepgram',
  },
  { id: 'groq', name: 'groq', status: 'adapted' as const, path: './connectors-adapted/groq' },
  {
    id: 'clearout',
    name: 'clearout',
    status: 'adapted' as const,
    path: './connectors-adapted/clearout',
  },
  {
    id: 'buttondown',
    name: 'buttondown',
    status: 'adapted' as const,
    path: './connectors-adapted/buttondown',
  },
  {
    id: 'runware',
    name: 'runware',
    status: 'adapted' as const,
    path: './connectors-adapted/runware',
  },
  {
    id: 'emailit',
    name: 'emailit',
    status: 'adapted' as const,
    path: './connectors-adapted/emailit',
  },
  {
    id: 'promotekit',
    name: 'promotekit',
    status: 'adapted' as const,
    path: './connectors-adapted/promotekit',
  },
  {
    id: 'hastewire',
    name: 'hastewire',
    status: 'adapted' as const,
    path: './connectors-adapted/hastewire',
  },
  {
    id: 'typeform',
    name: 'typeform',
    status: 'adapted' as const,
    path: './connectors-adapted/typeform',
  },
  {
    id: 'microsoft-365-planner',
    name: 'microsoft-365-planner',
    status: 'adapted' as const,
    path: './connectors-adapted/microsoft-365-planner',
  },
  { id: 'pdf-co', name: 'pdf-co', status: 'adapted' as const, path: './connectors-adapted/pdf-co' },
  {
    id: 'clickup',
    name: 'clickup',
    status: 'adapted' as const,
    path: './connectors-adapted/clickup',
  },
  {
    id: 'quickbooks',
    name: 'quickbooks',
    status: 'adapted' as const,
    path: './connectors-adapted/quickbooks',
  },
  {
    id: 'flow-helper',
    name: 'flow-helper',
    status: 'adapted' as const,
    path: './connectors-adapted/flow-helper',
  },
  {
    id: 'dappier',
    name: 'dappier',
    status: 'adapted' as const,
    path: './connectors-adapted/dappier',
  },
  { id: 'lusha', name: 'lusha', status: 'adapted' as const, path: './connectors-adapted/lusha' },
  {
    id: 'mailchimp',
    name: 'mailchimp',
    status: 'adapted' as const,
    path: './connectors-adapted/mailchimp',
  },
  {
    id: 'toggl-track',
    name: 'toggl-track',
    status: 'adapted' as const,
    path: './connectors-adapted/toggl-track',
  },
  {
    id: 'azure-devops',
    name: 'azure-devops',
    status: 'adapted' as const,
    path: './connectors-adapted/azure-devops',
  },
  {
    id: 'gravityforms',
    name: 'gravityforms',
    status: 'adapted' as const,
    path: './connectors-adapted/gravityforms',
  },
  {
    id: 'chatnode',
    name: 'chatnode',
    status: 'adapted' as const,
    path: './connectors-adapted/chatnode',
  },
  {
    id: 'google-cloud-storage',
    name: 'google-cloud-storage',
    status: 'adapted' as const,
    path: './connectors-adapted/google-cloud-storage',
  },
  { id: 'klipy', name: 'klipy', status: 'adapted' as const, path: './connectors-adapted/klipy' },
  { id: 'ninox', name: 'ninox', status: 'adapted' as const, path: './connectors-adapted/ninox' },
  {
    id: 'chargekeep',
    name: 'chargekeep',
    status: 'adapted' as const,
    path: './connectors-adapted/chargekeep',
  },
  {
    id: 'customgpt',
    name: 'customgpt',
    status: 'adapted' as const,
    path: './connectors-adapted/customgpt',
  },
  { id: 'frame', name: 'frame', status: 'adapted' as const, path: './connectors-adapted/frame' },
  { id: 'podio', name: 'podio', status: 'adapted' as const, path: './connectors-adapted/podio' },
  {
    id: 'parseur',
    name: 'parseur',
    status: 'adapted' as const,
    path: './connectors-adapted/parseur',
  },
  {
    id: 'hootsuite',
    name: 'hootsuite',
    status: 'adapted' as const,
    path: './connectors-adapted/hootsuite',
  },
  {
    id: 'rabbitmq',
    name: 'rabbitmq',
    status: 'adapted' as const,
    path: './connectors-adapted/rabbitmq',
  },
  { id: 'roe-ai', name: 'roe-ai', status: 'adapted' as const, path: './connectors-adapted/roe-ai' },
  { id: 'cody', name: 'cody', status: 'adapted' as const, path: './connectors-adapted/cody' },
  {
    id: 'moonclerk',
    name: 'moonclerk',
    status: 'adapted' as const,
    path: './connectors-adapted/moonclerk',
  },
  {
    id: 'serp-api',
    name: 'serp-api',
    status: 'adapted' as const,
    path: './connectors-adapted/serp-api',
  },
  { id: 'motion', name: 'motion', status: 'adapted' as const, path: './connectors-adapted/motion' },
  {
    id: 'snowflake',
    name: 'snowflake',
    status: 'adapted' as const,
    path: './connectors-adapted/snowflake',
  },
  { id: 'mcp', name: 'mcp', status: 'adapted' as const, path: './connectors-adapted/mcp' },
  {
    id: 'systeme-io',
    name: 'systeme-io',
    status: 'adapted' as const,
    path: './connectors-adapted/systeme-io',
  },
  {
    id: 'mailercheck',
    name: 'mailercheck',
    status: 'adapted' as const,
    path: './connectors-adapted/mailercheck',
  },
  { id: 'vbout', name: 'vbout', status: 'adapted' as const, path: './connectors-adapted/vbout' },
  {
    id: 'wayfront',
    name: 'wayfront',
    status: 'adapted' as const,
    path: './connectors-adapted/wayfront',
  },
  {
    id: 'sendinblue',
    name: 'sendinblue',
    status: 'adapted' as const,
    path: './connectors-adapted/sendinblue',
  },
  {
    id: 'youtrack',
    name: 'youtrack',
    status: 'adapted' as const,
    path: './connectors-adapted/youtrack',
  },
  {
    id: 'jira-cloud',
    name: 'jira-cloud',
    status: 'adapted' as const,
    path: './connectors-adapted/jira-cloud',
  },
  {
    id: 'whatsable',
    name: 'whatsable',
    status: 'adapted' as const,
    path: './connectors-adapted/whatsable',
  },
  {
    id: 'totalcms',
    name: 'totalcms',
    status: 'adapted' as const,
    path: './connectors-adapted/totalcms',
  },
  {
    id: 'intruder',
    name: 'intruder',
    status: 'adapted' as const,
    path: './connectors-adapted/intruder',
  },
  {
    id: 'anyhook-websocket',
    name: 'anyhook-websocket',
    status: 'adapted' as const,
    path: './connectors-adapted/anyhook-websocket',
  },
  { id: 'ampeco', name: 'ampeco', status: 'adapted' as const, path: './connectors-adapted/ampeco' },
  {
    id: 'proxycurl',
    name: 'proxycurl',
    status: 'adapted' as const,
    path: './connectors-adapted/proxycurl',
  },
  {
    id: 'teamleader',
    name: 'teamleader',
    status: 'adapted' as const,
    path: './connectors-adapted/teamleader',
  },
  {
    id: 'youtube',
    name: 'youtube',
    status: 'adapted' as const,
    path: './connectors-adapted/youtube',
  },
  {
    id: 'chainalysis-api',
    name: 'chainalysis-api',
    status: 'adapted' as const,
    path: './connectors-adapted/chainalysis-api',
  },
  { id: 'soap', name: 'soap', status: 'adapted' as const, path: './connectors-adapted/soap' },
  { id: 'pdf4me', name: 'pdf4me', status: 'adapted' as const, path: './connectors-adapted/pdf4me' },
  { id: 'postiz', name: 'postiz', status: 'adapted' as const, path: './connectors-adapted/postiz' },
  {
    id: 'digital-pilot',
    name: 'digital-pilot',
    status: 'adapted' as const,
    path: './connectors-adapted/digital-pilot',
  },
  {
    id: 'tiny-talk-ai',
    name: 'tiny-talk-ai',
    status: 'adapted' as const,
    path: './connectors-adapted/tiny-talk-ai',
  },
  { id: 'crisp', name: 'crisp', status: 'adapted' as const, path: './connectors-adapted/crisp' },
  {
    id: 'deepseek',
    name: 'deepseek',
    status: 'adapted' as const,
    path: './connectors-adapted/deepseek',
  },
  {
    id: 'uxsniff',
    name: 'uxsniff',
    status: 'adapted' as const,
    path: './connectors-adapted/uxsniff',
  },
  {
    id: 'synthesia',
    name: 'synthesia',
    status: 'adapted' as const,
    path: './connectors-adapted/synthesia',
  },
  {
    id: 'service-now',
    name: 'service-now',
    status: 'adapted' as const,
    path: './connectors-adapted/service-now',
  },
  { id: 'klenty', name: 'klenty', status: 'adapted' as const, path: './connectors-adapted/klenty' },
  {
    id: 'help-scout',
    name: 'help-scout',
    status: 'adapted' as const,
    path: './connectors-adapted/help-scout',
  },
  {
    id: 'raia-ai',
    name: 'raia-ai',
    status: 'adapted' as const,
    path: './connectors-adapted/raia-ai',
  },
  {
    id: 'bland-ai',
    name: 'bland-ai',
    status: 'adapted' as const,
    path: './connectors-adapted/bland-ai',
  },
  { id: 'linkup', name: 'linkup', status: 'adapted' as const, path: './connectors-adapted/linkup' },
  {
    id: 'camb-ai',
    name: 'camb-ai',
    status: 'adapted' as const,
    path: './connectors-adapted/camb-ai',
  },
  {
    id: 'checkout',
    name: 'checkout',
    status: 'adapted' as const,
    path: './connectors-adapted/checkout',
  },
  { id: 'saleor', name: 'saleor', status: 'adapted' as const, path: './connectors-adapted/saleor' },
  {
    id: 'certopus',
    name: 'certopus',
    status: 'adapted' as const,
    path: './connectors-adapted/certopus',
  },
  {
    id: 'splitwise',
    name: 'splitwise',
    status: 'adapted' as const,
    path: './connectors-adapted/splitwise',
  },
  {
    id: 'facebook-leads',
    name: 'facebook-leads',
    status: 'adapted' as const,
    path: './connectors-adapted/facebook-leads',
  },
  { id: 'bubble', name: 'bubble', status: 'adapted' as const, path: './connectors-adapted/bubble' },
  {
    id: 'mongodb',
    name: 'mongodb',
    status: 'adapted' as const,
    path: './connectors-adapted/mongodb',
  },
  {
    id: 'mixpanel',
    name: 'mixpanel',
    status: 'adapted' as const,
    path: './connectors-adapted/mixpanel',
  },
  { id: 'dub', name: 'dub', status: 'adapted' as const, path: './connectors-adapted/dub' },
  { id: 'notion', name: 'notion', status: 'adapted' as const, path: './connectors-adapted/notion' },
  {
    id: 'elevenlabs',
    name: 'elevenlabs',
    status: 'adapted' as const,
    path: './connectors-adapted/elevenlabs',
  },
  {
    id: 'pastebin',
    name: 'pastebin',
    status: 'adapted' as const,
    path: './connectors-adapted/pastebin',
  },
  {
    id: 'supabase',
    name: 'supabase',
    status: 'adapted' as const,
    path: './connectors-adapted/supabase',
  },
  {
    id: 'pocketbase',
    name: 'pocketbase',
    status: 'adapted' as const,
    path: './connectors-adapted/pocketbase',
  },
  { id: 'bokio', name: 'bokio', status: 'adapted' as const, path: './connectors-adapted/bokio' },
  {
    id: 'zoho-crm',
    name: 'zoho-crm',
    status: 'adapted' as const,
    path: './connectors-adapted/zoho-crm',
  },
  {
    id: 'azure-openai',
    name: 'azure-openai',
    status: 'adapted' as const,
    path: './connectors-adapted/azure-openai',
  },
  {
    id: 'instasent',
    name: 'instasent',
    status: 'adapted' as const,
    path: './connectors-adapted/instasent',
  },
  {
    id: 'google-calendar',
    name: 'google-calendar',
    status: 'adapted' as const,
    path: './connectors-adapted/google-calendar',
  },
  { id: 'zuora', name: 'zuora', status: 'adapted' as const, path: './connectors-adapted/zuora' },
  {
    id: 'afforai',
    name: 'afforai',
    status: 'adapted' as const,
    path: './connectors-adapted/afforai',
  },
  {
    id: 'brilliant-directories',
    name: 'brilliant-directories',
    status: 'adapted' as const,
    path: './connectors-adapted/brilliant-directories',
  },
  {
    id: 'retable',
    name: 'retable',
    status: 'adapted' as const,
    path: './connectors-adapted/retable',
  },
  {
    id: 'hubspot',
    name: 'hubspot',
    status: 'adapted' as const,
    path: './connectors-adapted/hubspot',
  },
  {
    id: 'pushover',
    name: 'pushover',
    status: 'adapted' as const,
    path: './connectors-adapted/pushover',
  },
  {
    id: 'emailoctopus',
    name: 'emailoctopus',
    status: 'adapted' as const,
    path: './connectors-adapted/emailoctopus',
  },
  {
    id: 'harvest',
    name: 'harvest',
    status: 'adapted' as const,
    path: './connectors-adapted/harvest',
  },
  {
    id: 'aiprise',
    name: 'aiprise',
    status: 'adapted' as const,
    path: './connectors-adapted/aiprise',
  },
  { id: 'xquik', name: 'xquik', status: 'adapted' as const, path: './connectors-adapted/xquik' },
  {
    id: 'aidbase',
    name: 'aidbase',
    status: 'adapted' as const,
    path: './connectors-adapted/aidbase',
  },
  {
    id: 'enrichlayer',
    name: 'enrichlayer',
    status: 'adapted' as const,
    path: './connectors-adapted/enrichlayer',
  },
  { id: 'wufoo', name: 'wufoo', status: 'adapted' as const, path: './connectors-adapted/wufoo' },
  {
    id: 'netlify',
    name: 'netlify',
    status: 'adapted' as const,
    path: './connectors-adapted/netlify',
  },
  {
    id: 'microsoft-outlook-calendar',
    name: 'microsoft-outlook-calendar',
    status: 'adapted' as const,
    path: './connectors-adapted/microsoft-outlook-calendar',
  },
  {
    id: 'mind-studio',
    name: 'mind-studio',
    status: 'adapted' as const,
    path: './connectors-adapted/mind-studio',
  },
  {
    id: 'pinecone',
    name: 'pinecone',
    status: 'adapted' as const,
    path: './connectors-adapted/pinecone',
  },
  {
    id: 'airtable',
    name: 'airtable',
    status: 'adapted' as const,
    path: './connectors-adapted/airtable',
  },
  {
    id: 'chat-aid',
    name: 'chat-aid',
    status: 'adapted' as const,
    path: './connectors-adapted/chat-aid',
  },
  {
    id: 'serpstat',
    name: 'serpstat',
    status: 'adapted' as const,
    path: './connectors-adapted/serpstat',
  },
  {
    id: 'heartbeat',
    name: 'heartbeat',
    status: 'adapted' as const,
    path: './connectors-adapted/heartbeat',
  },
  { id: 'tally', name: 'tally', status: 'adapted' as const, path: './connectors-adapted/tally' },
  {
    id: 'oracle-database',
    name: 'oracle-database',
    status: 'adapted' as const,
    path: './connectors-adapted/oracle-database',
  },
  {
    id: 'todoist',
    name: 'todoist',
    status: 'adapted' as const,
    path: './connectors-adapted/todoist',
  },
  {
    id: 'cashfree-payments',
    name: 'cashfree-payments',
    status: 'adapted' as const,
    path: './connectors-adapted/cashfree-payments',
  },
  {
    id: 'promptmate',
    name: 'promptmate',
    status: 'adapted' as const,
    path: './connectors-adapted/promptmate',
  },
  {
    id: 'seek-table',
    name: 'seek-table',
    status: 'adapted' as const,
    path: './connectors-adapted/seek-table',
  },
  {
    id: 'meistertask',
    name: 'meistertask',
    status: 'adapted' as const,
    path: './connectors-adapted/meistertask',
  },
  {
    id: 'algolia',
    name: 'algolia',
    status: 'adapted' as const,
    path: './connectors-adapted/algolia',
  },
  {
    id: 'robolly',
    name: 'robolly',
    status: 'adapted' as const,
    path: './connectors-adapted/robolly',
  },
  {
    id: 'griptape',
    name: 'griptape',
    status: 'adapted' as const,
    path: './connectors-adapted/griptape',
  },
  {
    id: 'azure-communication-services',
    name: 'azure-communication-services',
    status: 'adapted' as const,
    path: './connectors-adapted/azure-communication-services',
  },
  {
    id: 'aianswer',
    name: 'aianswer',
    status: 'adapted' as const,
    path: './connectors-adapted/aianswer',
  },
  {
    id: 'vidlab7',
    name: 'vidlab7',
    status: 'adapted' as const,
    path: './connectors-adapted/vidlab7',
  },
  {
    id: 'iloveapi',
    name: 'iloveapi',
    status: 'adapted' as const,
    path: './connectors-adapted/iloveapi',
  },
  {
    id: 'scenario',
    name: 'scenario',
    status: 'adapted' as const,
    path: './connectors-adapted/scenario',
  },
  {
    id: 'housecall-pro',
    name: 'housecall-pro',
    status: 'adapted' as const,
    path: './connectors-adapted/housecall-pro',
  },
  { id: 'linka', name: 'linka', status: 'adapted' as const, path: './connectors-adapted/linka' },
  {
    id: 'postgres',
    name: 'postgres',
    status: 'adapted' as const,
    path: './connectors-adapted/postgres',
  },
  {
    id: 'perplexity-ai',
    name: 'perplexity-ai',
    status: 'adapted' as const,
    path: './connectors-adapted/perplexity-ai',
  },
  {
    id: 'jina-ai',
    name: 'jina-ai',
    status: 'adapted' as const,
    path: './connectors-adapted/jina-ai',
  },
  {
    id: 'coralogix',
    name: 'coralogix',
    status: 'adapted' as const,
    path: './connectors-adapted/coralogix',
  },
  {
    id: 'neverbounce',
    name: 'neverbounce',
    status: 'adapted' as const,
    path: './connectors-adapted/neverbounce',
  },
  {
    id: 'oneclickimpact',
    name: 'oneclickimpact',
    status: 'adapted' as const,
    path: './connectors-adapted/oneclickimpact',
  },
  {
    id: 'blockscout',
    name: 'blockscout',
    status: 'adapted' as const,
    path: './connectors-adapted/blockscout',
  },
  {
    id: 'cloudconvert',
    name: 'cloudconvert',
    status: 'adapted' as const,
    path: './connectors-adapted/cloudconvert',
  },
  {
    id: 'onfleet',
    name: 'onfleet',
    status: 'adapted' as const,
    path: './connectors-adapted/onfleet',
  },
  { id: 'dimo', name: 'dimo', status: 'adapted' as const, path: './connectors-adapted/dimo' },
  { id: 'json', name: 'json', status: 'adapted' as const, path: './connectors-adapted/json' },
  {
    id: 'logrocket',
    name: 'logrocket',
    status: 'adapted' as const,
    path: './connectors-adapted/logrocket',
  },
  { id: 'gitea', name: 'gitea', status: 'adapted' as const, path: './connectors-adapted/gitea' },
  {
    id: 'barcode-lookup',
    name: 'barcode-lookup',
    status: 'adapted' as const,
    path: './connectors-adapted/barcode-lookup',
  },
  { id: 'wafeq', name: 'wafeq', status: 'adapted' as const, path: './connectors-adapted/wafeq' },
  {
    id: 'woodpecker',
    name: 'woodpecker',
    status: 'adapted' as const,
    path: './connectors-adapted/woodpecker',
  },
  {
    id: 'lucidya',
    name: 'lucidya',
    status: 'adapted' as const,
    path: './connectors-adapted/lucidya',
  },
  { id: 'wedof', name: 'wedof', status: 'adapted' as const, path: './connectors-adapted/wedof' },
  { id: 'gistly', name: 'gistly', status: 'adapted' as const, path: './connectors-adapted/gistly' },
  { id: 'zoo', name: 'zoo', status: 'adapted' as const, path: './connectors-adapted/zoo' },
  { id: 'github', name: 'github', status: 'adapted' as const, path: './connectors-adapted/github' },
  {
    id: 'stable-diffusion-webui',
    name: 'stable-diffusion-webui',
    status: 'adapted' as const,
    path: './connectors-adapted/stable-diffusion-webui',
  },
  {
    id: 'google-gemini',
    name: 'google-gemini',
    status: 'adapted' as const,
    path: './connectors-adapted/google-gemini',
  },
  { id: 'figma', name: 'figma', status: 'adapted' as const, path: './connectors-adapted/figma' },
  {
    id: 'open-router',
    name: 'open-router',
    status: 'adapted' as const,
    path: './connectors-adapted/open-router',
  },
  {
    id: 'zoho-bookings',
    name: 'zoho-bookings',
    status: 'adapted' as const,
    path: './connectors-adapted/zoho-bookings',
  },
  {
    id: 'beebole',
    name: 'beebole',
    status: 'adapted' as const,
    path: './connectors-adapted/beebole',
  },
  {
    id: 'everhour',
    name: 'everhour',
    status: 'adapted' as const,
    path: './connectors-adapted/everhour',
  },
  {
    id: 'chatsistant',
    name: 'chatsistant',
    status: 'adapted' as const,
    path: './connectors-adapted/chatsistant',
  },
  { id: 'fellow', name: 'fellow', status: 'adapted' as const, path: './connectors-adapted/fellow' },
  { id: 'webex', name: 'webex', status: 'adapted' as const, path: './connectors-adapted/webex' },
  { id: 'apollo', name: 'apollo', status: 'adapted' as const, path: './connectors-adapted/apollo' },
  {
    id: 'magical-api',
    name: 'magical-api',
    status: 'adapted' as const,
    path: './connectors-adapted/magical-api',
  },
  {
    id: 'google-sheets',
    name: 'google-sheets',
    status: 'adapted' as const,
    path: './connectors-adapted/google-sheets',
  },
  {
    id: 'kustomer',
    name: 'kustomer',
    status: 'adapted' as const,
    path: './connectors-adapted/kustomer',
  },
  { id: 'seven', name: 'seven', status: 'adapted' as const, path: './connectors-adapted/seven' },
  { id: 'line', name: 'line', status: 'adapted' as const, path: './connectors-adapted/line' },
  {
    id: 'fragment',
    name: 'fragment',
    status: 'adapted' as const,
    path: './connectors-adapted/fragment',
  },
  {
    id: 'jotform',
    name: 'jotform',
    status: 'adapted' as const,
    path: './connectors-adapted/jotform',
  },
  {
    id: 'zendesk',
    name: 'zendesk',
    status: 'adapted' as const,
    path: './connectors-adapted/zendesk',
  },
  {
    id: 'instagram-business',
    name: 'instagram-business',
    status: 'adapted' as const,
    path: './connectors-adapted/instagram-business',
  },
  {
    id: 'copy-ai',
    name: 'copy-ai',
    status: 'adapted' as const,
    path: './connectors-adapted/copy-ai',
  },
  {
    id: 'cartloom',
    name: 'cartloom',
    status: 'adapted' as const,
    path: './connectors-adapted/cartloom',
  },
  { id: 'tl-dv', name: 'tl-dv', status: 'adapted' as const, path: './connectors-adapted/tl-dv' },
  {
    id: 'elastic-email',
    name: 'elastic-email',
    status: 'adapted' as const,
    path: './connectors-adapted/elastic-email',
  },
  {
    id: 'deftform',
    name: 'deftform',
    status: 'adapted' as const,
    path: './connectors-adapted/deftform',
  },
  { id: 'heygen', name: 'heygen', status: 'adapted' as const, path: './connectors-adapted/heygen' },
  {
    id: 'google-drive',
    name: 'google-drive',
    status: 'adapted' as const,
    path: './connectors-adapted/google-drive',
  },
  {
    id: 'recurly',
    name: 'recurly',
    status: 'adapted' as const,
    path: './connectors-adapted/recurly',
  },
  {
    id: 'surveytale',
    name: 'surveytale',
    status: 'adapted' as const,
    path: './connectors-adapted/surveytale',
  },
  {
    id: 'uscreen',
    name: 'uscreen',
    status: 'adapted' as const,
    path: './connectors-adapted/uscreen',
  },
  { id: 'kapso', name: 'kapso', status: 'adapted' as const, path: './connectors-adapted/kapso' },
  {
    id: 'teamhood',
    name: 'teamhood',
    status: 'adapted' as const,
    path: './connectors-adapted/teamhood',
  },
  { id: 'kommo', name: 'kommo', status: 'adapted' as const, path: './connectors-adapted/kommo' },
  { id: 'ai', name: 'ai', status: 'adapted' as const, path: './connectors-adapted/ai' },
  {
    id: 'lemlist',
    name: 'lemlist',
    status: 'adapted' as const,
    path: './connectors-adapted/lemlist',
  },
  {
    id: 'gptzero-detect-ai',
    name: 'gptzero-detect-ai',
    status: 'adapted' as const,
    path: './connectors-adapted/gptzero-detect-ai',
  },
  { id: 'manus', name: 'manus', status: 'adapted' as const, path: './connectors-adapted/manus' },
  {
    id: 'apitemplate-io',
    name: 'apitemplate-io',
    status: 'adapted' as const,
    path: './connectors-adapted/apitemplate-io',
  },
  {
    id: 'straico',
    name: 'straico',
    status: 'adapted' as const,
    path: './connectors-adapted/straico',
  },
  { id: 'katana', name: 'katana', status: 'adapted' as const, path: './connectors-adapted/katana' },
  {
    id: 'gcloud-pubsub',
    name: 'gcloud-pubsub',
    status: 'adapted' as const,
    path: './connectors-adapted/gcloud-pubsub',
  },
  { id: 'qwilr', name: 'qwilr', status: 'adapted' as const, path: './connectors-adapted/qwilr' },
  {
    id: 'smartlead',
    name: 'smartlead',
    status: 'adapted' as const,
    path: './connectors-adapted/smartlead',
  },
  {
    id: 'browserless',
    name: 'browserless',
    status: 'adapted' as const,
    path: './connectors-adapted/browserless',
  },
  { id: 'mollie', name: 'mollie', status: 'adapted' as const, path: './connectors-adapted/mollie' },
  { id: 'mysql', name: 'mysql', status: 'adapted' as const, path: './connectors-adapted/mysql' },
  {
    id: 'bluesky',
    name: 'bluesky',
    status: 'adapted' as const,
    path: './connectors-adapted/bluesky',
  },
  {
    id: 'zoho-mail',
    name: 'zoho-mail',
    status: 'adapted' as const,
    path: './connectors-adapted/zoho-mail',
  },
  {
    id: 'retell-ai',
    name: 'retell-ai',
    status: 'adapted' as const,
    path: './connectors-adapted/retell-ai',
  },
  {
    id: 'vouchery-io',
    name: 'vouchery-io',
    status: 'adapted' as const,
    path: './connectors-adapted/vouchery-io',
  },
  {
    id: 'cloutly',
    name: 'cloutly',
    status: 'adapted' as const,
    path: './connectors-adapted/cloutly',
  },
  {
    id: 'voipstudio',
    name: 'voipstudio',
    status: 'adapted' as const,
    path: './connectors-adapted/voipstudio',
  },
  {
    id: 'mailer-lite',
    name: 'mailer-lite',
    status: 'adapted' as const,
    path: './connectors-adapted/mailer-lite',
  },
  {
    id: 'outseta',
    name: 'outseta',
    status: 'adapted' as const,
    path: './connectors-adapted/outseta',
  },
  {
    id: 'call-rounded',
    name: 'call-rounded',
    status: 'adapted' as const,
    path: './connectors-adapted/call-rounded',
  },
  { id: 'fathom', name: 'fathom', status: 'adapted' as const, path: './connectors-adapted/fathom' },
  {
    id: 'millionverifier',
    name: 'millionverifier',
    status: 'adapted' as const,
    path: './connectors-adapted/millionverifier',
  },
  { id: 'shippo', name: 'shippo', status: 'adapted' as const, path: './connectors-adapted/shippo' },
  { id: 'reddit', name: 'reddit', status: 'adapted' as const, path: './connectors-adapted/reddit' },
  {
    id: 'supadata',
    name: 'supadata',
    status: 'adapted' as const,
    path: './connectors-adapted/supadata',
  },
  { id: 'okta', name: 'okta', status: 'adapted' as const, path: './connectors-adapted/okta' },
  {
    id: 'amazon-ses',
    name: 'amazon-ses',
    status: 'adapted' as const,
    path: './connectors-adapted/amazon-ses',
  },
  {
    id: 'useinbox',
    name: 'useinbox',
    status: 'adapted' as const,
    path: './connectors-adapted/useinbox',
  },
  {
    id: 'datadog',
    name: 'datadog',
    status: 'adapted' as const,
    path: './connectors-adapted/datadog',
  },
  { id: 'folk', name: 'folk', status: 'adapted' as const, path: './connectors-adapted/folk' },
  {
    id: 'sitespeakai',
    name: 'sitespeakai',
    status: 'adapted' as const,
    path: './connectors-adapted/sitespeakai',
  },
  { id: 'pubrio', name: 'pubrio', status: 'adapted' as const, path: './connectors-adapted/pubrio' },
  {
    id: 'feathery',
    name: 'feathery',
    status: 'adapted' as const,
    path: './connectors-adapted/feathery',
  },
  {
    id: 'confluence',
    name: 'confluence',
    status: 'adapted' as const,
    path: './connectors-adapted/confluence',
  },
  {
    id: 'carbone',
    name: 'carbone',
    status: 'adapted' as const,
    path: './connectors-adapted/carbone',
  },
  {
    id: 'hugging-face',
    name: 'hugging-face',
    status: 'adapted' as const,
    path: './connectors-adapted/hugging-face',
  },
  {
    id: 'assemblyai',
    name: 'assemblyai',
    status: 'adapted' as const,
    path: './connectors-adapted/assemblyai',
  },
  {
    id: 'kallabot-ai',
    name: 'kallabot-ai',
    status: 'adapted' as const,
    path: './connectors-adapted/kallabot-ai',
  },
  {
    id: 'eden-ai',
    name: 'eden-ai',
    status: 'adapted' as const,
    path: './connectors-adapted/eden-ai',
  },
  {
    id: 'docsbot',
    name: 'docsbot',
    status: 'adapted' as const,
    path: './connectors-adapted/docsbot',
  },
  {
    id: 'ticktick',
    name: 'ticktick',
    status: 'adapted' as const,
    path: './connectors-adapted/ticktick',
  },
  { id: 'deepl', name: 'deepl', status: 'adapted' as const, path: './connectors-adapted/deepl' },
  {
    id: 'bursty-ai',
    name: 'bursty-ai',
    status: 'adapted' as const,
    path: './connectors-adapted/bursty-ai',
  },
  { id: 'bolna', name: 'bolna', status: 'adapted' as const, path: './connectors-adapted/bolna' },
  { id: 'qdrant', name: 'qdrant', status: 'adapted' as const, path: './connectors-adapted/qdrant' },
  { id: 'queue', name: 'queue', status: 'adapted' as const, path: './connectors-adapted/queue' },
  {
    id: 'assembled',
    name: 'assembled',
    status: 'adapted' as const,
    path: './connectors-adapted/assembled',
  },
  { id: 'retune', name: 'retune', status: 'adapted' as const, path: './connectors-adapted/retune' },
  {
    id: 'googlechat',
    name: 'googlechat',
    status: 'adapted' as const,
    path: './connectors-adapted/googlechat',
  },
  {
    id: 'discourse',
    name: 'discourse',
    status: 'adapted' as const,
    path: './connectors-adapted/discourse',
  },
  {
    id: 'documerge',
    name: 'documerge',
    status: 'adapted' as const,
    path: './connectors-adapted/documerge',
  },
  { id: 'zoom', name: 'zoom', status: 'adapted' as const, path: './connectors-adapted/zoom' },
  {
    id: 'pandadoc',
    name: 'pandadoc',
    status: 'adapted' as const,
    path: './connectors-adapted/pandadoc',
  },
  {
    id: 'contextual-ai',
    name: 'contextual-ai',
    status: 'adapted' as const,
    path: './connectors-adapted/contextual-ai',
  },
  { id: 'base44', name: 'base44', status: 'adapted' as const, path: './connectors-adapted/base44' },
  {
    id: 'flowise',
    name: 'flowise',
    status: 'adapted' as const,
    path: './connectors-adapted/flowise',
  },
  {
    id: 'dropbox',
    name: 'dropbox',
    status: 'adapted' as const,
    path: './connectors-adapted/dropbox',
  },
  {
    id: 'murf-api',
    name: 'murf-api',
    status: 'adapted' as const,
    path: './connectors-adapted/murf-api',
  },
  {
    id: 'amazon-s3',
    name: 'amazon-s3',
    status: 'adapted' as const,
    path: './connectors-adapted/amazon-s3',
  },
  {
    id: 'videoask',
    name: 'videoask',
    status: 'adapted' as const,
    path: './connectors-adapted/videoask',
  },
  {
    id: 'capsule-crm',
    name: 'capsule-crm',
    status: 'adapted' as const,
    path: './connectors-adapted/capsule-crm',
  },
  {
    id: 'anyhook-graphql',
    name: 'anyhook-graphql',
    status: 'adapted' as const,
    path: './connectors-adapted/anyhook-graphql',
  },
  {
    id: 'logsnag',
    name: 'logsnag',
    status: 'adapted' as const,
    path: './connectors-adapted/logsnag',
  },
  {
    id: 'mysendingbox',
    name: 'mysendingbox',
    status: 'adapted' as const,
    path: './connectors-adapted/mysendingbox',
  },
  {
    id: 'pushbullet',
    name: 'pushbullet',
    status: 'adapted' as const,
    path: './connectors-adapted/pushbullet',
  },
  { id: 'duckdb', name: 'duckdb', status: 'adapted' as const, path: './connectors-adapted/duckdb' },
  {
    id: 'microsoft-dynamics-crm',
    name: 'microsoft-dynamics-crm',
    status: 'adapted' as const,
    path: './connectors-adapted/microsoft-dynamics-crm',
  },
  {
    id: 'saastic',
    name: 'saastic',
    status: 'adapted' as const,
    path: './connectors-adapted/saastic',
  },
  { id: 'gotify', name: 'gotify', status: 'adapted' as const, path: './connectors-adapted/gotify' },
  {
    id: 'microsoft-todo',
    name: 'microsoft-todo',
    status: 'adapted' as const,
    path: './connectors-adapted/microsoft-todo',
  },
  {
    id: 'bonjoro',
    name: 'bonjoro',
    status: 'adapted' as const,
    path: './connectors-adapted/bonjoro',
  },
  { id: 'loops', name: 'loops', status: 'adapted' as const, path: './connectors-adapted/loops' },
  {
    id: 'chatling',
    name: 'chatling',
    status: 'adapted' as const,
    path: './connectors-adapted/chatling',
  },
  {
    id: 'salesforce',
    name: 'salesforce',
    status: 'adapted' as const,
    path: './connectors-adapted/salesforce',
  },
  { id: 'ashby', name: 'ashby', status: 'adapted' as const, path: './connectors-adapted/ashby' },
  {
    id: 'chatfly',
    name: 'chatfly',
    status: 'adapted' as const,
    path: './connectors-adapted/chatfly',
  },
  {
    id: 'jogg-ai',
    name: 'jogg-ai',
    status: 'adapted' as const,
    path: './connectors-adapted/jogg-ai',
  },
  { id: 'circle', name: 'circle', status: 'adapted' as const, path: './connectors-adapted/circle' },
  {
    id: 'mailgun',
    name: 'mailgun',
    status: 'adapted' as const,
    path: './connectors-adapted/mailgun',
  },
  {
    id: 'insightly',
    name: 'insightly',
    status: 'adapted' as const,
    path: './connectors-adapted/insightly',
  },
  {
    id: 'alttextify',
    name: 'alttextify',
    status: 'adapted' as const,
    path: './connectors-adapted/alttextify',
  },
  { id: 'tidely', name: 'tidely', status: 'adapted' as const, path: './connectors-adapted/tidely' },
  {
    id: 'week-done',
    name: 'week-done',
    status: 'adapted' as const,
    path: './connectors-adapted/week-done',
  },
  {
    id: 'echowin',
    name: 'echowin',
    status: 'adapted' as const,
    path: './connectors-adapted/echowin',
  },
  {
    id: 'amazon-secrets-manager',
    name: 'amazon-secrets-manager',
    status: 'adapted' as const,
    path: './connectors-adapted/amazon-secrets-manager',
  },
  { id: 'slack', name: 'slack', status: 'adapted' as const, path: './connectors-adapted/slack' },
  {
    id: 'whatsscale',
    name: 'whatsscale',
    status: 'adapted' as const,
    path: './connectors-adapted/whatsscale',
  },
  {
    id: 'descript',
    name: 'descript',
    status: 'adapted' as const,
    path: './connectors-adapted/descript',
  },
  {
    id: 'formbricks',
    name: 'formbricks',
    status: 'adapted' as const,
    path: './connectors-adapted/formbricks',
  },
  {
    id: 'pastefy',
    name: 'pastefy',
    status: 'adapted' as const,
    path: './connectors-adapted/pastefy',
  },
  {
    id: 'simpliroute',
    name: 'simpliroute',
    status: 'adapted' as const,
    path: './connectors-adapted/simpliroute',
  },
  { id: 'avoma', name: 'avoma', status: 'adapted' as const, path: './connectors-adapted/avoma' },
  {
    id: 'mattermost',
    name: 'mattermost',
    status: 'adapted' as const,
    path: './connectors-adapted/mattermost',
  },
  {
    id: 'zoho-desk',
    name: 'zoho-desk',
    status: 'adapted' as const,
    path: './connectors-adapted/zoho-desk',
  },
  {
    id: 'phantombuster',
    name: 'phantombuster',
    status: 'adapted' as const,
    path: './connectors-adapted/phantombuster',
  },
  {
    id: 'posthog',
    name: 'posthog',
    status: 'adapted' as const,
    path: './connectors-adapted/posthog',
  },
  {
    id: 'metabase',
    name: 'metabase',
    status: 'adapted' as const,
    path: './connectors-adapted/metabase',
  },
  {
    id: 'greenpt',
    name: 'greenpt',
    status: 'adapted' as const,
    path: './connectors-adapted/greenpt',
  },
  { id: 'twenty', name: 'twenty', status: 'adapted' as const, path: './connectors-adapted/twenty' },
  { id: 'bika', name: 'bika', status: 'adapted' as const, path: './connectors-adapted/bika' },
  {
    id: 'slidespeak',
    name: 'slidespeak',
    status: 'adapted' as const,
    path: './connectors-adapted/slidespeak',
  },
  {
    id: 'lets-calendar',
    name: 'lets-calendar',
    status: 'adapted' as const,
    path: './connectors-adapted/lets-calendar',
  },
  {
    id: 'predict-leads',
    name: 'predict-leads',
    status: 'adapted' as const,
    path: './connectors-adapted/predict-leads',
  },
  {
    id: 'razorpay',
    name: 'razorpay',
    status: 'adapted' as const,
    path: './connectors-adapted/razorpay',
  },
  {
    id: 'google-slides',
    name: 'google-slides',
    status: 'adapted' as const,
    path: './connectors-adapted/google-slides',
  },
  {
    id: 'contiguity',
    name: 'contiguity',
    status: 'adapted' as const,
    path: './connectors-adapted/contiguity',
  },
  {
    id: 'recall-ai',
    name: 'recall-ai',
    status: 'adapted' as const,
    path: './connectors-adapted/recall-ai',
  },
  {
    id: 'customer-io',
    name: 'customer-io',
    status: 'adapted' as const,
    path: './connectors-adapted/customer-io',
  },
  {
    id: 'cryptolens',
    name: 'cryptolens',
    status: 'adapted' as const,
    path: './connectors-adapted/cryptolens',
  },
  {
    id: 'amazon-bedrock',
    name: 'amazon-bedrock',
    status: 'adapted' as const,
    path: './connectors-adapted/amazon-bedrock',
  },
  { id: 'trello', name: 'trello', status: 'adapted' as const, path: './connectors-adapted/trello' },
  {
    id: 'google-bigquery',
    name: 'google-bigquery',
    status: 'adapted' as const,
    path: './connectors-adapted/google-bigquery',
  },
  {
    id: 'surveymonkey',
    name: 'surveymonkey',
    status: 'adapted' as const,
    path: './connectors-adapted/surveymonkey',
  },
  {
    id: 'extracta-ai',
    name: 'extracta-ai',
    status: 'adapted' as const,
    path: './connectors-adapted/extracta-ai',
  },
  {
    id: 'reoon-verifier',
    name: 'reoon-verifier',
    status: 'adapted' as const,
    path: './connectors-adapted/reoon-verifier',
  },
  {
    id: 'free-agent',
    name: 'free-agent',
    status: 'adapted' as const,
    path: './connectors-adapted/free-agent',
  },
  {
    id: 'fathom-analytics',
    name: 'fathom-analytics',
    status: 'adapted' as const,
    path: './connectors-adapted/fathom-analytics',
  },
  { id: 'grist', name: 'grist', status: 'adapted' as const, path: './connectors-adapted/grist' },
  {
    id: 'google-my-business',
    name: 'google-my-business',
    status: 'adapted' as const,
    path: './connectors-adapted/google-my-business',
  },
  {
    id: 'clockify',
    name: 'clockify',
    status: 'adapted' as const,
    path: './connectors-adapted/clockify',
  },
  {
    id: 'constant-contact',
    name: 'constant-contact',
    status: 'adapted' as const,
    path: './connectors-adapted/constant-contact',
  },
  {
    id: 'clearoutphone',
    name: 'clearoutphone',
    status: 'adapted' as const,
    path: './connectors-adapted/clearoutphone',
  },
  { id: 'tavily', name: 'tavily', status: 'adapted' as const, path: './connectors-adapted/tavily' },
  {
    id: 'bookedin',
    name: 'bookedin',
    status: 'adapted' as const,
    path: './connectors-adapted/bookedin',
  },
  {
    id: 'facebook-pages',
    name: 'facebook-pages',
    status: 'adapted' as const,
    path: './connectors-adapted/facebook-pages',
  },
  {
    id: 'beehiiv',
    name: 'beehiiv',
    status: 'adapted' as const,
    path: './connectors-adapted/beehiiv',
  },
  { id: 'sendy', name: 'sendy', status: 'adapted' as const, path: './connectors-adapted/sendy' },
  { id: 'ko-fi', name: 'ko-fi', status: 'adapted' as const, path: './connectors-adapted/ko-fi' },
  {
    id: 'dittofeed',
    name: 'dittofeed',
    status: 'adapted' as const,
    path: './connectors-adapted/dittofeed',
  },
  {
    id: 'simplepdf',
    name: 'simplepdf',
    status: 'adapted' as const,
    path: './connectors-adapted/simplepdf',
  },
  {
    id: 'clicdata',
    name: 'clicdata',
    status: 'adapted' as const,
    path: './connectors-adapted/clicdata',
  },
  {
    id: 'gameball',
    name: 'gameball',
    status: 'adapted' as const,
    path: './connectors-adapted/gameball',
  },
  {
    id: 'add-event',
    name: 'add-event',
    status: 'adapted' as const,
    path: './connectors-adapted/add-event',
  },
  { id: 'nifty', name: 'nifty', status: 'adapted' as const, path: './connectors-adapted/nifty' },
  {
    id: 'wootric',
    name: 'wootric',
    status: 'adapted' as const,
    path: './connectors-adapted/wootric',
  },
  {
    id: 'krisp-call',
    name: 'krisp-call',
    status: 'adapted' as const,
    path: './connectors-adapted/krisp-call',
  },
  {
    id: 'calendly',
    name: 'calendly',
    status: 'adapted' as const,
    path: './connectors-adapted/calendly',
  },
  {
    id: 'reply-io',
    name: 'reply-io',
    status: 'adapted' as const,
    path: './connectors-adapted/reply-io',
  },
  {
    id: 'amazon-textract',
    name: 'amazon-textract',
    status: 'adapted' as const,
    path: './connectors-adapted/amazon-textract',
  },
  {
    id: 'clarifai',
    name: 'clarifai',
    status: 'adapted' as const,
    path: './connectors-adapted/clarifai',
  },
  {
    id: 'medullar',
    name: 'medullar',
    status: 'adapted' as const,
    path: './connectors-adapted/medullar',
  },
  {
    id: 'bumpups',
    name: 'bumpups',
    status: 'adapted' as const,
    path: './connectors-adapted/bumpups',
  },
  {
    id: 'eth-name-service',
    name: 'eth-name-service',
    status: 'adapted' as const,
    path: './connectors-adapted/eth-name-service',
  },
  {
    id: 'weekdone',
    name: 'weekdone',
    status: 'adapted' as const,
    path: './connectors-adapted/weekdone',
  },
  {
    id: 'digital-ocean',
    name: 'digital-ocean',
    status: 'adapted' as const,
    path: './connectors-adapted/digital-ocean',
  },
  {
    id: 'fireflies-ai',
    name: 'fireflies-ai',
    status: 'adapted' as const,
    path: './connectors-adapted/fireflies-ai',
  },
  { id: 'avian', name: 'avian', status: 'adapted' as const, path: './connectors-adapted/avian' },
  {
    id: 'gender-api',
    name: 'gender-api',
    status: 'adapted' as const,
    path: './connectors-adapted/gender-api',
  },
  { id: 'sperse', name: 'sperse', status: 'adapted' as const, path: './connectors-adapted/sperse' },
  {
    id: 'opportify',
    name: 'opportify',
    status: 'adapted' as const,
    path: './connectors-adapted/opportify',
  },
  {
    id: 'uptimerobot',
    name: 'uptimerobot',
    status: 'adapted' as const,
    path: './connectors-adapted/uptimerobot',
  },
  {
    id: 'ninjapipe',
    name: 'ninjapipe',
    status: 'adapted' as const,
    path: './connectors-adapted/ninjapipe',
  },
  { id: 'tenzo', name: 'tenzo', status: 'adapted' as const, path: './connectors-adapted/tenzo' },
  {
    id: 'mistral-ai',
    name: 'mistral-ai',
    status: 'adapted' as const,
    path: './connectors-adapted/mistral-ai',
  },
  {
    id: 'respaid',
    name: 'respaid',
    status: 'adapted' as const,
    path: './connectors-adapted/respaid',
  },
  { id: 'twitch', name: 'twitch', status: 'adapted' as const, path: './connectors-adapted/twitch' },
  {
    id: 'formstack',
    name: 'formstack',
    status: 'adapted' as const,
    path: './connectors-adapted/formstack',
  },
  {
    id: 'insta-charts',
    name: 'insta-charts',
    status: 'adapted' as const,
    path: './connectors-adapted/insta-charts',
  },
  {
    id: 'short-io',
    name: 'short-io',
    status: 'adapted' as const,
    path: './connectors-adapted/short-io',
  },
  {
    id: 'netsuite',
    name: 'netsuite',
    status: 'adapted' as const,
    path: './connectors-adapted/netsuite',
  },
  { id: 'doctly', name: 'doctly', status: 'adapted' as const, path: './connectors-adapted/doctly' },
  {
    id: 'missive',
    name: 'missive',
    status: 'adapted' as const,
    path: './connectors-adapted/missive',
  },
  {
    id: 'cometapi',
    name: 'cometapi',
    status: 'adapted' as const,
    path: './connectors-adapted/cometapi',
  },
  {
    id: 'thankster',
    name: 'thankster',
    status: 'adapted' as const,
    path: './connectors-adapted/thankster',
  },
  {
    id: 'asknews',
    name: 'asknews',
    status: 'adapted' as const,
    path: './connectors-adapted/asknews',
  },
  { id: 'front', name: 'front', status: 'adapted' as const, path: './connectors-adapted/front' },
  {
    id: 'zerobounce',
    name: 'zerobounce',
    status: 'adapted' as const,
    path: './connectors-adapted/zerobounce',
  },
  { id: 'canny', name: 'canny', status: 'adapted' as const, path: './connectors-adapted/canny' },
  { id: 'beamer', name: 'beamer', status: 'adapted' as const, path: './connectors-adapted/beamer' },
  { id: 'alai', name: 'alai', status: 'adapted' as const, path: './connectors-adapted/alai' },
  {
    id: 'connectuc',
    name: 'connectuc',
    status: 'adapted' as const,
    path: './connectors-adapted/connectuc',
  },
  { id: 'airtop', name: 'airtop', status: 'adapted' as const, path: './connectors-adapted/airtop' },
  {
    id: 'billplz',
    name: 'billplz',
    status: 'adapted' as const,
    path: './connectors-adapted/billplz',
  },
  { id: 'letta', name: 'letta', status: 'adapted' as const, path: './connectors-adapted/letta' },
  {
    id: 'lightfunnels',
    name: 'lightfunnels',
    status: 'adapted' as const,
    path: './connectors-adapted/lightfunnels',
  },
  {
    id: 'formspark',
    name: 'formspark',
    status: 'adapted' as const,
    path: './connectors-adapted/formspark',
  },
  {
    id: 'pollybot-ai',
    name: 'pollybot-ai',
    status: 'adapted' as const,
    path: './connectors-adapted/pollybot-ai',
  },
  {
    id: 'upgradechat',
    name: 'upgradechat',
    status: 'adapted' as const,
    path: './connectors-adapted/upgradechat',
  },
  { id: 'kimai', name: 'kimai', status: 'adapted' as const, path: './connectors-adapted/kimai' },
  { id: 'matrix', name: 'matrix', status: 'adapted' as const, path: './connectors-adapted/matrix' },
  {
    id: 'nuelink',
    name: 'nuelink',
    status: 'adapted' as const,
    path: './connectors-adapted/nuelink',
  },
  {
    id: 'sendpulse',
    name: 'sendpulse',
    status: 'adapted' as const,
    path: './connectors-adapted/sendpulse',
  },
  {
    id: 'feedhive',
    name: 'feedhive',
    status: 'adapted' as const,
    path: './connectors-adapted/feedhive',
  },
  {
    id: 'documentpro',
    name: 'documentpro',
    status: 'adapted' as const,
    path: './connectors-adapted/documentpro',
  },
  { id: 'asana', name: 'asana', status: 'adapted' as const, path: './connectors-adapted/asana' },
  { id: 'knock', name: 'knock', status: 'adapted' as const, path: './connectors-adapted/knock' },
  {
    id: 'gorgias',
    name: 'gorgias',
    status: 'adapted' as const,
    path: './connectors-adapted/gorgias',
  },
  { id: 'coda', name: 'coda', status: 'adapted' as const, path: './connectors-adapted/coda' },
  {
    id: 'reachinbox',
    name: 'reachinbox',
    status: 'adapted' as const,
    path: './connectors-adapted/reachinbox',
  },
  {
    id: 'google-search-console',
    name: 'google-search-console',
    status: 'adapted' as const,
    path: './connectors-adapted/google-search-console',
  },
  {
    id: 'webling',
    name: 'webling',
    status: 'adapted' as const,
    path: './connectors-adapted/webling',
  },
  {
    id: 'leap-ai',
    name: 'leap-ai',
    status: 'adapted' as const,
    path: './connectors-adapted/leap-ai',
  },
  {
    id: 'skyprep',
    name: 'skyprep',
    status: 'adapted' as const,
    path: './connectors-adapted/skyprep',
  },
  { id: 'apify', name: 'apify', status: 'adapted' as const, path: './connectors-adapted/apify' },
  {
    id: 'aircall',
    name: 'aircall',
    status: 'adapted' as const,
    path: './connectors-adapted/aircall',
  },
  {
    id: 'datafuel',
    name: 'datafuel',
    status: 'adapted' as const,
    path: './connectors-adapted/datafuel',
  },
  { id: 'gmail', name: 'gmail', status: 'adapted' as const, path: './connectors-adapted/gmail' },
  {
    id: 'luxury-presence',
    name: 'luxury-presence',
    status: 'adapted' as const,
    path: './connectors-adapted/luxury-presence',
  },
  {
    id: 'flow-parser',
    name: 'flow-parser',
    status: 'adapted' as const,
    path: './connectors-adapted/flow-parser',
  },
  {
    id: 'quickzu',
    name: 'quickzu',
    status: 'adapted' as const,
    path: './connectors-adapted/quickzu',
  },
  { id: 'vapi', name: 'vapi', status: 'adapted' as const, path: './connectors-adapted/vapi' },
  {
    id: 'lemon-squeezy',
    name: 'lemon-squeezy',
    status: 'adapted' as const,
    path: './connectors-adapted/lemon-squeezy',
  },
  {
    id: 'taskade',
    name: 'taskade',
    status: 'adapted' as const,
    path: './connectors-adapted/taskade',
  },
  { id: 'agentx', name: 'agentx', status: 'adapted' as const, path: './connectors-adapted/agentx' },
  {
    id: 'moveo-ai',
    name: 'moveo-ai',
    status: 'adapted' as const,
    path: './connectors-adapted/moveo-ai',
  },
  {
    id: 'whatsapp',
    name: 'whatsapp',
    status: 'adapted' as const,
    path: './connectors-adapted/whatsapp',
  },
  { id: 'knack', name: 'knack', status: 'adapted' as const, path: './connectors-adapted/knack' },
  {
    id: 'bettermode',
    name: 'bettermode',
    status: 'adapted' as const,
    path: './connectors-adapted/bettermode',
  },
  {
    id: 'dumpling-ai',
    name: 'dumpling-ai',
    status: 'adapted' as const,
    path: './connectors-adapted/dumpling-ai',
  },
  { id: 'resend', name: 'resend', status: 'adapted' as const, path: './connectors-adapted/resend' },
  {
    id: 'skyvern',
    name: 'skyvern',
    status: 'adapted' as const,
    path: './connectors-adapted/skyvern',
  },
  {
    id: 'pdfcrowd',
    name: 'pdfcrowd',
    status: 'adapted' as const,
    path: './connectors-adapted/pdfcrowd',
  },
  {
    id: 'google-contacts',
    name: 'google-contacts',
    status: 'adapted' as const,
    path: './connectors-adapted/google-contacts',
  },
  {
    id: 'youcanbookme',
    name: 'youcanbookme',
    status: 'adapted' as const,
    path: './connectors-adapted/youcanbookme',
  },
  { id: 'openai', name: 'openai', status: 'adapted' as const, path: './connectors-adapted/openai' },
  { id: 'sardis', name: 'sardis', status: 'adapted' as const, path: './connectors-adapted/sardis' },
  {
    id: 'microsoft-onenote',
    name: 'microsoft-onenote',
    status: 'adapted' as const,
    path: './connectors-adapted/microsoft-onenote',
  },
  {
    id: 'microsoft-outlook',
    name: 'microsoft-outlook',
    status: 'adapted' as const,
    path: './connectors-adapted/microsoft-outlook',
  },
  {
    id: 'browse-ai',
    name: 'browse-ai',
    status: 'adapted' as const,
    path: './connectors-adapted/browse-ai',
  },
  {
    id: 'linkedin',
    name: 'linkedin',
    status: 'adapted' as const,
    path: './connectors-adapted/linkedin',
  },
  {
    id: 'ibm-cognose',
    name: 'ibm-cognose',
    status: 'adapted' as const,
    path: './connectors-adapted/ibm-cognose',
  },
  { id: 'mem', name: 'mem', status: 'adapted' as const, path: './connectors-adapted/mem' },
  {
    id: 'activepieces',
    name: 'activepieces',
    status: 'adapted' as const,
    path: './connectors-adapted/activepieces',
  },
  { id: 'matomo', name: 'matomo', status: 'adapted' as const, path: './connectors-adapted/matomo' },
  {
    id: 'stability-ai',
    name: 'stability-ai',
    status: 'adapted' as const,
    path: './connectors-adapted/stability-ai',
  },
  {
    id: 'motiontools',
    name: 'motiontools',
    status: 'adapted' as const,
    path: './connectors-adapted/motiontools',
  },
  { id: 'twilio', name: 'twilio', status: 'adapted' as const, path: './connectors-adapted/twilio' },
  { id: 'stripe', name: 'stripe', status: 'adapted' as const, path: './connectors-adapted/stripe' },
  {
    id: 'binance',
    name: 'binance',
    status: 'adapted' as const,
    path: './connectors-adapted/binance',
  },
  {
    id: 'metatext',
    name: 'metatext',
    status: 'adapted' as const,
    path: './connectors-adapted/metatext',
  },
  {
    id: 'teamwork',
    name: 'teamwork',
    status: 'adapted' as const,
    path: './connectors-adapted/teamwork',
  },
  { id: 'buffer', name: 'buffer', status: 'adapted' as const, path: './connectors-adapted/buffer' },
  {
    id: 'vlm-run',
    name: 'vlm-run',
    status: 'adapted' as const,
    path: './connectors-adapted/vlm-run',
  },
  {
    id: 'instantly-ai',
    name: 'instantly-ai',
    status: 'adapted' as const,
    path: './connectors-adapted/instantly-ai',
  },
  {
    id: 'photoroom',
    name: 'photoroom',
    status: 'adapted' as const,
    path: './connectors-adapted/photoroom',
  },
  {
    id: 'appfollow',
    name: 'appfollow',
    status: 'adapted' as const,
    path: './connectors-adapted/appfollow',
  },
  {
    id: 'couchbase',
    name: 'couchbase',
    status: 'adapted' as const,
    path: './connectors-adapted/couchbase',
  },
  {
    id: 'giftbit',
    name: 'giftbit',
    status: 'adapted' as const,
    path: './connectors-adapted/giftbit',
  },
  { id: 'slack', name: 'Slack', status: 'ready' as const, path: './connectors/slack' },
  { id: 'github', name: 'GitHub', status: 'ready' as const, path: './connectors/github' },
  { id: 'gmail', name: 'Gmail', status: 'ready' as const, path: './connectors/gmail' },
  { id: 'linear', name: 'Linear', status: 'ready' as const, path: './connectors/linear' },
  { id: 'notion', name: 'Notion', status: 'ready' as const, path: './connectors/notion' },
] as const;
export const CONNECTOR_COUNT = 711;
